version: "3"

volumes:
  api_node_modules:
  front_node_modules:

services:

  db:
    container_name: downote_db
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./mysqlVars.env
    environment:
      MYSQL_ROOT_PASSWORD: roop
      
  api:
    container_name: downote_api
    build:
      context: ./downote-api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "127.0.0.1:8082:8082"
    env_file:
      - ./mysqlVars.env
    environment:
      API_HOST: api
      API_PORT: 8082
      DB_HOST: db
    volumes:
      - api_node_modules:/home/downote/app/node_modules/
  
  front:
    container_name: downote_front
    build:
      context: ./downote-front
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - front_node_modules:/home/downote/app/node_modules/
